Repository appuio/terraform-modules, pull requests merged in 2022-10, with the labels that each got.

#32 vshn-lbaas-exoscale: Set encdata zone for LB VMs
  modules/vshn-lbaas-exoscale/files/register-server.sh
Labels: bug

#30 vshn-lbaas-exoscale: Update module for Exoscale provider v0.41.0
  modules/vshn-lbaas-exoscale/README.md
  modules/vshn-lbaas-exoscale/hiera.tf
  modules/vshn-lbaas-exoscale/main.tf
  modules/vshn-lbaas-exoscale/outputs.tf
  modules/vshn-lbaas-exoscale/providers.tf
  modules/vshn-lbaas-exoscale/security_groups.tf
  modules/vshn-lbaas-exoscale/variables.tf
Labels: breaking

#33 vshn-lbaas-exoscale: Generate Floaty IAM API key via Terraform
  modules/vshn-lbaas-exoscale/hiera.tf
  modules/vshn-lbaas-exoscale/variables.tf
Labels: enhancement

#35 Update vshn-lbaas-exoscale README.md
  modules/vshn-lbaas-exoscale/README.md
Labels: ignore

#34 vshn-lbaas-exoscale: Allow users to customize the LB instance type
  modules/vshn-lbaas-exoscale/README.md
  modules/vshn-lbaas-exoscale/main.tf
  modules/vshn-lbaas-exoscale/variables.tf
Labels: enhancement

#36 vshn-lbaas-exoscale: Adjust security group rules to simplify migration of existing clusters
  modules/vshn-lbaas-exoscale/security_groups.tf
Labels: ignore

#37 vshn-lbaas-exoscale: Use FQDN as compute instance `name`
  modules/vshn-lbaas-exoscale/main.tf
Labels: bug

#38 vshn-lbaas-exoscale: Add support for configuring deployment target ID
  modules/vshn-lbaas-exoscale/README.md
  modules/vshn-lbaas-exoscale/main.tf
  modules/vshn-lbaas-exoscale/variables.tf
Labels: enhancement
